services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 9001:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: